meta_product_name: "Post Meridiem"
meta_title: "Your perfect evening just around the corner"
meta_description: "All the bars resteraunts and cafes around in your area at your fingertips"
meta_image: "dave-lastovskiy-127581-unsplash.jpg"                       # should exist in `app/assets/images/`
